// <auto-generated />
using H4SS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H4SS.Migrations.TodoDb
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20250410074943_UpdatedTodoContext")]
    partial class UpdatedTodoContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H4SS.Data.Cpr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CprNr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Cpr__3214EC07B603CEB1");

                    b.ToTable("Cpr", (string)null);
                });

            modelBuilder.Entity("H4SS.Data.Todolist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Todolist__3214EC07191F8783");

                    b.HasIndex("UserId");

                    b.ToTable("Todolist", (string)null);
                });

            modelBuilder.Entity("H4SS.Data.Todolist", b =>
                {
                    b.HasOne("H4SS.Data.Cpr", "User")
                        .WithMany("Todolists")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Todolist_Cpr");

                    b.Navigation("User");
                });

            modelBuilder.Entity("H4SS.Data.Cpr", b =>
                {
                    b.Navigation("Todolists");
                });
#pragma warning restore 612, 618
        }
    }
}
